feat(webgpu-rendering-context): import webgpu renderer
techlauncher-mlai-edge-physics/CFlowSim pull request #99
Opened 2023-09-11 12:34 UTC by esterTion

This PR finishes #74

2023-09-12 00:29 UTC, Lutra-Fs requested changes
node_modules\three\examples\jsm\capabilities\WebGPU.js
or how do we add the three addons? needs to specify these instructions first.

2023-09-12 03:35 UTC, esterTion commented
they are already in the three package, and import will work with current configuration. 
the only thing required is typescript declaration of the type, since these modules are not released yet

2023-09-12 05:20 UTC, Lutra-Fs requested changes

2023-09-12 05:20 UTC, Lutra-Fs commented on src/components/Simulation.tsx
> +  if ( WebGPU.isAvailable() === true ) {
```
CFlowSim\src\components\Simulation.tsx
  68:8   error  Unsafe call of an `any` typed value  @typescript-eslint/no-unsafe-call
  69:11  error  Unsafe assignment of an `any` value  @typescript-eslint/no-unsafe-assignment
```
line returns these errors in `npm run lint`

2023-09-12 05:20 UTC, Lutra-Fs commented on src/components/Simulation.tsx
> +  if ( WebGPU.isAvailable() === true ) {
Also pls make sure that you have configured `prettier` as the formatter.

2023-09-12 05:21 UTC, Lutra-Fs commented
> they are already in the three package, and import will work with current configuration. the only thing required is typescript declaration of the type, since these modules are not released yet

Understood. pls resolve format and linting error to get it merged

2023-09-12 06:53 UTC, Lutra-Fs approved these changes
LGTM

2023-09-13 13:26 UTC, peipacut approved these changes

2023-09-14 04:58 UTC, merged